// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Altro: 'Other', // UNUSED
  'Elezioni maggio 2021': 'Elections May 2021', // UNUSED
  Programmi: 'Programs', // UNUSED
  Risultati: 'Results', // UNUSED
  'COORDINA I CORSI DI STUDIO E FORNISCE UN INDIRIZZO GENERALE ALLA SCUOLA.': 'COORDINATES THE COURSES OF STUDY AND PROVIDES A GENERAL ADDRESS TO THE SCHOOL.', // UNUSED
  'Contatti 💬': 'Contacts 💬', // UNUSED
  'Elezioni rappresentanti degli studenti': 'Election of student representatives', // UNUSED
  Scrivici: 'Write to us', // UNUSED
  Scuole: 'Schools', // UNUSED
  'Sito Principale': 'Main Website',
  'Progetti Interessanti:': 'Interesting Projects:'
}
