// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Altro: 'Altro', // UNUSED
  'Elezioni maggio 2021': 'Elezioni maggio 2021', // UNUSED
  Programmi: 'Programmi', // UNUSED
  Risultati: 'Risultati', // UNUSED
  'COORDINA I CORSI DI STUDIO E FORNISCE UN INDIRIZZO GENERALE ALLA SCUOLA.': 'COORDINA I CORSI DI STUDIO E FORNISCE UN INDIRIZZO GENERALE ALLA SCUOLA.', // UNUSED
  'Contatti 💬': 'Contatti 💬', // UNUSED
  'Elezioni rappresentanti degli studenti': 'Elezioni rappresentanti degli studenti', // UNUSED
  Scrivici: 'Scrivici', // UNUSED
  Scuole: 'Scuole', // UNUSED
  'Abbiamo l\'obiettivo di costruire una rete coesa di studenti, per gli studenti.': 'Abbiamo l\'obiettivo di costruire una rete coesa di studenti, per gli studenti.'
}
